name: digit_widget
description: Widget set to display numbers of radix 10 (decimal), 16 (hexidecimal) or any other one
# Widget "Digit" to display numbers of a specific radix:
# -----------------------------------------------
# 2: binary,
# 10: decimal,
# 16: hexidecimal
# or any other, if you don't expect special characters, other than decimal number, A to F for hexidecimal numbers
# special digits:
#  * '<space>': all off
#  * '=': (closest) to equal sign
#  * '-': dash
#  * '_': underscore
#  * '[xX]': an "x" character
#
# Widget "Colon" to display a separator for e.g. time exposure of clocks, like '21:05'
# Widget "Separator": Dedicated to improve readability of single digit within number rows
# * decimalPoint: bool: Shows a decimal point
# * thousand

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true